import fs from 'fs-extra'
import path from 'path'

export async function generateFeatureGates(
  destination: string,
  featureCodes: string[]
): Promise<void> {
  if (featureCodes.length === 0) return

  const libPath = path.join(destination, 'lib')
  await fs.ensureDir(libPath)

  // Generate lib/feature-gates.ts
  const featureGatesContent = `// Auto-generated by create-nozle-app
// Feature gates based on environment variables

export const FEATURES = {
${featureCodes.map((code) => `  ${code}: process.env.NEXT_PUBLIC_FEATURE_${code.toUpperCase()} === 'true',`).join('\n')}
} as const

export type FeatureCode = keyof typeof FEATURES

export function hasFeature(feature: FeatureCode): boolean {
  return FEATURES[feature]
}

export function getEnabledFeatures(): FeatureCode[] {
  return Object.entries(FEATURES)
    .filter(([_, enabled]) => enabled)
    .map(([code]) => code as FeatureCode)
}
`

  await fs.writeFile(
    path.join(libPath, 'feature-gates.ts'),
    featureGatesContent,
    'utf-8'
  )
}

export async function generateMiddleware(
  destination: string,
  featureCodes: string[],
  template: 'app-router-ts' | 'pages-router-ts'
): Promise<void> {
  if (featureCodes.length === 0) return

  const middlewareContent = `import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

// Feature-gated routes
// Add routes that require specific features here
const GATED_ROUTES: Record<string, string> = {
  // Example: '/dashboard/analytics': 'advanced_analytics',
${featureCodes.map((code) => `  // '/path': '${code}',`).join('\n')}
}

export async function middleware(request: NextRequest) {
  const pathname = request.nextUrl.pathname
  const requiredFeature = GATED_ROUTES[pathname]

  if (requiredFeature) {
    // Get customer ID from your auth system
    // This is a placeholder - integrate with your actual auth
    const customerId = request.headers.get('x-customer-id') || request.cookies.get('customer_id')?.value

    if (!customerId) {
      return NextResponse.redirect(new URL('/login', request.url))
    }

    // Check entitlement server-side
    // Uncomment when you have a server-side can() implementation
    /*
    const { nozle } = await import('./lib/nozle-client')
    const result = await nozle.can(customerId, requiredFeature)

    if (!result.allowed) {
      return NextResponse.json(
        { error: 'Feature not available in your plan', reason: result.reason },
        { status: 403 }
      )
    }
    */
  }

  return NextResponse.next()
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}
`

  await fs.writeFile(
    path.join(destination, 'middleware.ts'),
    middlewareContent,
    'utf-8'
  )
}

export function generateFeatureEnvVars(featureCodes: string[]): Record<string, boolean> {
  const features: Record<string, boolean> = {}

  // Default all features to false - user can enable them based on their plan
  for (const code of featureCodes) {
    features[code] = false
  }

  return features
}
